server:
  port: 8080

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 421431368218-12qqkdim8li3i78coui5s4jfu3q3dmv6.apps.googleusercontent.com
            client-secret: RN6_0R3MGmP4LyBH5LJ8hvdP
          synd:
            client-id: c00001
            client-secret: password
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: profile,source_read,synd_read
            client-name: Synd
        provider:
          synd:
            authorization-uri: http://ramustha.com:9999/oauth/authorize
            token-uri: http://ramustha.com:9999/oauth/token
            jwk-set-uri: http://ramustha.com:9999/.well-known/jwks.json
            user-info-uri: http://ramustha.com:9999/oauth/userinfo
            user-info-authentication-method: header
            user-name-attribute: sub

resource-uri: http://localhost:9000

logging:
  level:
#    ROOT: INFO
    com.ramusthastudio: DEBUG