server:
  port: 9000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9999/.well-known/jwks.json

logging:
  level:
    #    ROOT: INFO
    com.ramusthastudio: DEBUG